# Increase memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Loom is not yet compatible with the configuration cache.
org.gradle.configuration-cache=false

# Fabric versions - check these at https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.20

# Mod properties
version=1.0.0
group=dev.cowgirlfraust

# Dependencies
fabric_api_version=0.155.2+26.1.2
fabric_language_kotlin_version=1.13.13+kotlin.2.4.10
kotlin_version=2.4.10
dev_auth_neo_version=1.1.1
